[project]
name = "robogame"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "adafruit-circuitpython-pca9685>=3.4.22",
    "blinker>=1.9.0",
    "opencv-python>=4.13.0.92",
]

[tool.uv.workspace]
members = [
    ".",
]

[tool.uv.sources]
robogame = { workspace = true }

[dependency-groups]
dev = [
    "robogame",
]
