[project]
name = "robogame"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "blinker>=1.9.0",
]

[tool.uv.workspace]
members = [
    ".",
]

[tool.uv.sources]
robogame = { workspace = true }

[dependency-groups]
dev = [
    "robogame",
]
